In [1]:
import numpy as np

np.random.seed(0)

random_data = np.random.randint(10,size=(10,10))

In [2]:
random_data

array([[5, 0, 3, 3, 7, 9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1, 6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4, 3, 0, 3, 5, 0],
       [2, 3, 8, 1, 3, 3, 3, 7, 0, 1],
       [9, 9, 0, 4, 7, 3, 2, 7, 2, 0],
       [0, 4, 5, 5, 6, 8, 4, 1, 4, 9],
       [8, 1, 1, 7, 9, 9, 3, 6, 7, 2],
       [0, 3, 5, 9, 4, 4, 6, 4, 4, 3],
       [4, 4, 8, 4, 3, 7, 5, 5, 0, 1],
       [5, 9, 3, 0, 5, 0, 1, 2, 4, 2]])

In [3]:
random_data[4:7,2:8]


array([[0, 4, 7, 3, 2, 7],
       [5, 5, 6, 8, 4, 1],
       [1, 7, 9, 9, 3, 6]])

In [4]:
random_data[:5,:3]


array([[5, 0, 3],
       [7, 6, 8],
       [5, 9, 8],
       [2, 3, 8],
       [9, 9, 0]])

In [5]:
random_data[-3:,-5:]

array([[4, 6, 4, 4, 3],
       [7, 5, 5, 0, 1],
       [0, 1, 2, 4, 2]])

In [6]:
#Uniendo Matrices

m1 = np.array([1,2,3],[4,5,6])

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [7]:
m1 = np.array([[1,2,3],[4,5,6]])
m2 = np.array([[1,2,3],[4,5,6]])

np.concatenate([m1,m2],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [8]:
np.concatenate([m1,m2],axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [9]:
np.concatenate([m1,m2],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [10]:
#Usar split, lo que hace es que corta el arreglo en la posicion que dices
x = [1,2,3,10,11,12,20,21,22]

x1,x2,x3 = np.split(x,[3,6])

x1

array([1, 2, 3])

In [11]:
x2
x3

array([20, 21, 22])

In [12]:
x3

array([20, 21, 22])

In [13]:
x2

array([10, 11, 12])

In [14]:
#Transformar a matriz
matriz = np.array(x).reshape((3,3))
matriz

array([[ 1,  2,  3],
       [10, 11, 12],
       [20, 21, 22]])

Universal Functions

In [3]:
import numpy as np

In [4]:
values = np.random.randint(1,100,size=100)

print(values)

[84 45 77 24 69  5 24  2 73 61 88 56  4 42 76 74 34 25 73 93 48 22 41 52
 33 52 39 74 69 66 68 97 28 70 60 87 84 55 92 81 51 58 53 80 40 37  9 59
 70 76 92 50 49 73 49 32 98 93 71 95 52 99 26 79 26 39 51 29 65 53 55 74
 58 97 11 40 66 88  3 55 53 52 73 71  4 24  1 23 86 83 28 35 67 61 31 77
  2 14 57 47]


In [5]:
def reduce_10_percent(data) :   ##Se reduce el 10% de cada valor del arreglo
    result=[]
    for number in data:
        reduced =  number * 0.9
        result.append(reduced)
        
    return result

In [7]:
%timeit reduce_10_percent(values)  ##Te dice el tiempo que toma el proceso.

293 µs ± 2.89 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [9]:
result = values*0.9  ##Esto es una universal Function
result


array([75.6, 40.5, 69.3, 21.6, 62.1,  4.5, 21.6,  1.8, 65.7, 54.9, 79.2,
       50.4,  3.6, 37.8, 68.4, 66.6, 30.6, 22.5, 65.7, 83.7, 43.2, 19.8,
       36.9, 46.8, 29.7, 46.8, 35.1, 66.6, 62.1, 59.4, 61.2, 87.3, 25.2,
       63. , 54. , 78.3, 75.6, 49.5, 82.8, 72.9, 45.9, 52.2, 47.7, 72. ,
       36. , 33.3,  8.1, 53.1, 63. , 68.4, 82.8, 45. , 44.1, 65.7, 44.1,
       28.8, 88.2, 83.7, 63.9, 85.5, 46.8, 89.1, 23.4, 71.1, 23.4, 35.1,
       45.9, 26.1, 58.5, 47.7, 49.5, 66.6, 52.2, 87.3,  9.9, 36. , 59.4,
       79.2,  2.7, 49.5, 47.7, 46.8, 65.7, 63.9,  3.6, 21.6,  0.9, 20.7,
       77.4, 74.7, 25.2, 31.5, 60.3, 54.9, 27.9, 69.3,  1.8, 12.6, 51.3,
       42.3])

In [10]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [11]:
x+5

array([5, 6, 7, 8])

In [12]:
x-5

array([-5, -4, -3, -2])

In [13]:
x*2

array([0, 2, 4, 6])

In [14]:
x/2

array([0. , 0.5, 1. , 1.5])

In [15]:
-x

array([ 0, -1, -2, -3])

In [16]:
x**2

array([0, 1, 4, 9])

In [17]:
##Se pueden realizar funciones matematicas a los arreglos
fx = x**2 + 5

In [18]:
fx


array([ 5,  6,  9, 14])

In [19]:
x = np.arange(5)
y= np.arange(5)

x*y

array([ 0,  1,  4,  9, 16])

In [20]:
x = np.arange(5)
y= np.arange(4)

x[:4]*y

array([0, 1, 4, 9])

In [21]:
np.absolute(x)

array([0, 1, 2, 3, 4])

In [22]:
x = np.arange(5)
y = np.random.random(5)

print(x)

[0 1 2 3 4]


In [23]:
print(y)


[0.64459395 0.61731679 0.37961784 0.61759963 0.06620091]


In [24]:
x * y

array([0.        , 0.61731679, 0.75923567, 1.85279888, 0.26480365])

In [28]:
data = np.linspace(0,5,10)
data

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [29]:
#np.sin(), np.cos(), np.tan()
#np.arcsin(), np.arcos(), np.arctan()
#np.exp(), np.log(), np.log

In [30]:
#scipy son funciones orientadas a la ciencia

In [32]:
data = np.random.random(100)

data.sum()

57.823405220394264

In [33]:
data.min()

0.0319867383943907

In [34]:
data.max()

0.9930911624163348

In [35]:
a =  np.arange(3)

b= np.arange(3).reshape(3,1)

a
b

array([[0],
       [1],
       [2]])

In [36]:
a

array([0, 1, 2])

In [37]:
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])