In [2]:
import numpy as np

In [2]:
np.random.seed(0) #Siempre Obtiene los mismos numeros aleatorios

x1 = np. random.randint(10,size = 10)

x2 = np.random.randint(10,size = (3,3))

x3 = np.random.randint(10,size=(3,4,5))

In [3]:
print(x1)

[5 0 3 3 7 9 3 5 2 4]


In [4]:
print(x2)
print(x3)

[[7 6 8]
 [8 1 6]
 [7 7 8]]
[[[1 5 9 8 9]
  [4 3 0 3 5]
  [0 2 3 8 1]
  [3 3 3 7 0]]

 [[1 9 9 0 4]
  [7 3 2 7 2]
  [0 0 4 5 5]
  [6 8 4 1 4]]

 [[9 8 1 1 7]
  [9 9 3 6 7]
  [2 0 3 5 9]
  [4 4 6 4 4]]]


In [3]:
numeros = np.array([1,2,3,4,5])

# Indexación
numeros[1

2

In [4]:
#Array Slicing

In [5]:
# x[start:stop:step]

x = np.arange(10)

In [6]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#Obtiene los elementos desde la posición 0 hasta la 5
x[0:5]

array([0, 1, 2, 3, 4])

In [8]:
#Obtiene los primeros 5 elementos
x[:5]

array([0, 1, 2, 3, 4])

In [9]:
#Obtiene los elementos desde la posición 5
x[5:]

array([5, 6, 7, 8, 9])

In [10]:
#Obtiene los elementos de la posición 2 a la 7

x[2:7]

array([2, 3, 4, 5, 6])

In [12]:
#Obtiene los elementos de la posición 2 a la 7, de 2 en 2

x[2:7:2]

array([2, 4, 6])

In [13]:
# Revertir el arreglo

x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [14]:
pares = x[2:7:2]

pares [::-1]

In [5]:
x[7:2:-1]

NameError: name 'x' is not defined